drop table SIMPSONS_CHARACTER;

CREATE TABLE SIMPSONS_CHARACTER( 
   id LONG NOT NULL, 
   FIRST_NAME VARCHAR(50) NOT NULL, 
   LAST_NAME VARCHAR(50) NOT NULL, 
   PICTURE VARCHAR(150) NOT NULL, 
   AGE INT NOT NULL, 
   QUOTE VARCHAR(150) NOT NULL

);


commit;

select * from SIMPSONS_CHARACTER ;